# Generated by Django 5.2.7 on 2025-11-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("funding_round", models.CharField(max_length=50)),
                ("funding", models.DecimalField(decimal_places=2, max_digits=15)),
                ("location", models.CharField(max_length=255)),
                ("num_employees", models.IntegerField()),
                ("founding_year", models.IntegerField()),
                ("growth_percentage", models.IntegerField()),
            ],
        ),
    ]
