# Generated by Django 5.2.7 on 2025-12-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="sector",
            field=models.CharField(default="Other", max_length=100),
            preserve_default=False,
        ),
    ]
