# Generated by Django 5.2.7 on 2025-12-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_company_sector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="growth_percentage",
        ),
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
